#ifndef __XMR_CONSTANTS_H__
#define __XMR_CONSTANTS_H__

#define XMR_MAX_MIXIN_LEVEL 9
#define XMR_MAX_MIXIN_COUNT (XMR_MAX_MIXIN_LEVEL + 1)
#define XMR_MAX_VIN_COUNT   4096
#define XMR_MAX_VOUT_COUNT  4096
#define XMR_MAX_EXTRA_SIZE  8192

#define XMR_MAX_OUT_ADDRESSES 10

#define XMR_ATOMIC_UNIT   1e12
#define XMR_TX_FEE_PER_KB 2e9

#define XMR_PUBLIC_ADDRESS_BASE58_PREFIX                    18U
#define XMR_PUBLIC_INTEGRATED_ADDRESS_BASE58_PREFIX         19U
#define XMR_TESTNET_PUBLIC_ADDRESS_BASE58_PREFIX            53U
#define XMR_TESTNET_PUBLIC_INTEGRATED_ADDRESS_BASE58_PREFIX 54U

#define XMR_TX_EXTRA_TAG_PUBKEY                 0x01
#define XMR_TX_EXTRA_NONCE                      0x02
#define XMR_TX_EXTRA_NONCE_PAYMENT_ID           0x00
#define XMR_TX_EXTRA_NONCE_ENCRYPTED_PAYMENT_ID 0x01

#define XMR_ENCRYPTED_PAYMENT_ID_TAIL 0x8d
#define XMR_ENCRYPTED_PAYMENT_ID_SIZE 8U
#define XMR_DEFAULT_PAYMENT_ID_SIZE	  32U

#define XMR_ADDRESS_CHECKSUM_SIZE 4U

#endif
